### ISSUE TITLE
ERROR: Failed at the grunt-phantomcss@0.2.3 postinstall script

### ISSUE THREAD

**Issue by stayko16** [chrisgladd/grunt-phantomcss#27]
Im getting the following error when trying to install: 

npm ERR! grunt-phantomcss@0.2.3 postinstall: node ./node_modules/bower/bin/bower install
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunt-phantomcss@0.2.3 postinstall script.
npm ERR! This is most likely a problem with the grunt-phantomcss package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-phantomcss
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-phantomcss"
npm ERR! cwd /Users/s.chalakov/work/nap-product-details-presentation
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/s.chalakov/work/nap-product-details-presentation/npm-debug.log
npm ERR! not ok code 0`

Anyone have any ideas why?

**Comment by tomsky** [comment]
+1

**Comment by diegoeis** [comment]
No success @nagarajhubli.

`
npm ERR! grunt-phantomcss-working-version@0.2.3 preinstall: 'npm install bower && bower install'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunt-phantomcss-working-version@0.2.3 preinstall script 'npm install bower && bower install'.
npm ERR! This is most likely a problem with the grunt-phantomcss-working-version package,
`

**Comment by brunowego** [comment]
+1

**Comment by dishui** [comment]
with both the grunt-phantomcss and grunt-phantomcss-working-version, I get the errors:
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bower"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: bower-config@'>=0.2.0 <0.3.0'

it seems that it does not work with npm v2.11.2.  
Wonder if you could fix the bower version according to this : https://github.com/chrisgladd/grunt-phantomcss/issues/38

So that the modules can be used with npm install

**Comment by chrisgladd** [comment]
Fixed in v0.3.0
